//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ban_REMOTE_MSSQL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class ban_setting : global::System.Configuration.ApplicationSettingsBase {
        
        private static ban_setting defaultInstance = ((ban_setting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ban_setting())));
        
        public static ban_setting Default {
            get {
                return defaultInstance;
            }
        }
    }
}
